In [74]:
!python solution_to_snapchat_like_filters.py

(485, 377, 3)
(221, 483, 4)
(320, 640, 4)


In [70]:
import numpy as np
x=np.array([[[1,2],[3,4]],[[2,3],[4,5]],[[3,4],[5,6]]])
print(x)
print(x.shape)

[[[1 2]
  [3 4]]

 [[2 3]
  [4 5]]

 [[3 4]
  [5 6]]]
(3, 2, 2)


In [71]:
x=x.reshape((-1,2))
print(x)
print(x.shape)

[[1 2]
 [3 4]
 [2 3]
 [4 5]
 [3 4]
 [5 6]]
(6, 2)
