In [1]:
!python solution_to_snapchat_like_filters.py

cv2.error: OpenCV(4.2.0) /io/opencv/modules/objdetect/src/cascadedetect.cpp:569: error: (-2:Unspecified error) in function 'bool cv::HaarEvaluator::Feature::read(const cv::FileNode&, const Size&)'
> Invalid HAAR feature (expected: 'rw.r.x + rw.r.width <= W'), where
>     'rw.r.x + rw.r.width' is 22
> must be less than or equal to
>     'W' is 16


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "solution_to_snapchat_like_filters.py", line 5, in <module>
    eye_cascade=cv2.CascadeClassifier("/home/muskan/mydata/ML-Projects-code/challenges/Challenge5 - Make snapchat like filters/frontalEyes35x16.xml")
SystemError: <class 'cv2.CascadeClassifier'> returned a result with an error set


In [7]:
import numpy as np
x=np.array([[[1,2],[3,4]],[[2,3],[4,5]],[[3,4],[5,6]]])
print(x)
print(x.shape)

[[[1 2]
  [3 4]]

 [[2 3]
  [4 5]]

 [[3 4]
  [5 6]]]
(3, 2, 2)


In [8]:
x=x.reshape((-1,2))
print(x)
print(x.shape)

[[1 2]
 [3 4]
 [2 3]
 [4 5]
 [3 4]
 [5 6]]
(6, 2)
